version: '3'

networks:
    dock_bill:

services:

    api_dock_bill:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: api_dock_bill
        ports:
            - "3333:3333"
        depends_on:
            - postgres
        networks:
            - dock_bill

    postgres:
        image: postgres
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "postgres"
            POSTGRES_DB: "dock_bill"
        ports:
            - "5432:5432"
        networks:
        - dock_bill
