version: '3'

networks:
    dock_bill:

services:

    postgres:
        image: postgres
        container_name: postgres_dock_bill
        restart: unless-stopped
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "postgres"
            POSTGRES_DB: "dock_bill"
        ports:
            - "5432:5432"
        networks:
            - dock_bill

    api_dock_bill:
        build:
            context: .
        container_name: api_dock_bill
        depends_on:
            - postgres
        ports:
            - "3333:3333"
        networks:
            - dock_bill
