version: '3'

services:

    postgres:
        image: postgres
        container_name: postgres_dock_bill
        restart: unless-stopped
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "postgres"
            POSTGRES_DB: "dock_bill"
        ports:
            - "5432:5432"

    api_dock_bill:
        container_name: api_dock_bill
        depends_on:
            - postgres
        build:
            target: production
            context: .
            dockerfile: app.Dockerfile
        volumes:
            - ./:/app-prod
        ports:
            - "3333:3333"
        environment:
            - ENV=production
        command: npm run start
